name: Check Links

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 18 1 * *" # Monthly on the 1st at 6 PM UTC

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
      pull-requests: write # required for PR comments
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0 && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

      - name: Read Lychee Report
        if: steps.lychee.outputs.exit_code != 0 && github.event_name == 'pull_request'
        id: lychee_report
        run: |
          if [ -f ./lychee/out.md ]; then
            echo "content<<EOF" >> $GITHUB_OUTPUT
            cat ./lychee/out.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "content=No detailed report available." >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with Link Check Results
        if: steps.lychee.outputs.exit_code != 0 && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## 🔗 Link Checker Report

            Some links failed to check. See details below:

            ${{ steps.lychee_report.outputs.content }}
