name: Deploy to GitHub Pages and PR Previews

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write # Needed to comment on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr.outputs.number }}
    steps:
      - uses: actions/checkout@v4

      - name: Get PR number
        id: get_pr
        if: github.event_name == 'pull_request'
        run: echo "number=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build site
        run: |
          npm ci
          npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy-main:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: site

      - name: Deploy PR preview to gh-pages/pr-N
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          destination_dir: pr-${{ needs.build.outputs.pr_number }}
          publish_branch: gh-pages
          keep_files: true # Prevent overwriting main page

      - name: Comment with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-url
          message: |
            🚀 Preview ready:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ needs.build.outputs.pr_number }}
